travis:
  secure:
    BINSTAR_TOKEN: VdliLSem3NtPeIdfTBDqJ7SRt7gOBor7Uhk5gryNNOWEUkDgSA72ghU3Pdmivyc3DeK+Z8aCgMaRvtpnA+2hmVsSkqbNHcPA8CXFOZp21xwvqqgNxv8CgZvp28YBubbpfi6+4FT7xawbt/Zx+Z2cYJXDs6tLjqAAd8Xq56vww/s4ABzOpBepPOG9tfOTsIrSzWLDttnEy0frpagFc5CkrNj0zMrf6DjMdNGQkXuGdS4InfHm8A+dhktPrtV8MScmlXH/oK0jCVT0CdU98OGUXUjjzcJ9ttvIykJ4I3JB7Rfy/3OD9c3dcmjSy9ap/z86HWFQ0ZcZYPACNwiw/nY7zJxj2WiHBD7JRnotbET7HQmqHVwdnDUi2MqfrEv+lax7dhhv6xG9Uvz9KaauNisBtgdf+HuHovG8kegavcMzKbPwmV6l9t9zOYkHDNBxrTfowwrttL73w2JNw51cvMWPeMQPL5rF296woC8AF4x3xXnV/huh98UMZ9psduYzAC3Mwk6356hT6EFgBPpSHbXo5roXD7t+jl+ieR79UZdrcuLGTInfAPh44+Mt31h/okkq2tCqfoaUIlxaI5kLgRRpzuIUP7znkvbojZFDEjp3KjI52ZiTQ5M09XFoohwZQim9clSJbfR/51PH/xNpw2aQMIUHsqip9kAauuB8o5W+2jo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
