travis:
  secure:
    BINSTAR_TOKEN: dLiU1O5M1mEriNrCu1zLYoIDMwPzB9kwumxDZXSpeHk3B6Ad/epgP6449jEbPn85PDYm+8vrwPNdPczK85sLgnlcr6YmrCX6rUGwscKXre/10uFyyiKRgoE2lRYuHsdZnfbPXn3YXbNs0bEjSuZt1ZaSOHFGdY1AZNCG0TdmxGb0XF3zxGr1vGMOMToC/z6PH+EeJEE/1o4txJFUNYsPyGEyZAvaH4Uel1T6UeokM3P20L5dUVJFUJ3B3eR/ZHPOcxHWwktd/Nlu4JQl3A+HLXBOveIKBW0AlwdoRHJFywIJdhcyfyNxyHQ1bXzDjROUbIBsnURhxnpl0g5qm8SBEJfXmuwBXAVDsCRJY818ZnKgvdxm5euITNqj2ry22tzrEF9zl67UKqIW27udfxeuRV1dLcwwBlmeCTf+nKlRbEY4bFu1+FAvpn3kz9VwmdLykFVQ8T7mwceM3vun9rUci+Cc/YumIMZbwh14Naaa9GbG+5gTiioXmR73hfc1DbmK3bfoMkpWKUf2/EMmLRkSHl+EJuthKdMQK31U0OPYxGas+EBrc8Xgj1QKlXufzaR8Yx8GxJHr+h0iNN+XaUTs00y0RCE/LhLyTo9NRgBObRyCIn/HfzNehWfxUiXQWXacscu1QLNq6CebwCpn2OuPsUbRvKkBqlOI51PQk0boAlg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
