travis:
  secure:
    BINSTAR_TOKEN: T7KXyLOvhCm88OOeNULcF/PL4/O9nPQaHJDgKEBJkgS793SaTVUqmmrZ3fiVWj4i3WoRikKZeHE5GNz3r9XdOl1GM/1yyQLPYBNprS+m9fBaFt+gLurrzVMyEYoDFM9QyCkmw4CmfQm+zxYGHEmjEKO48FUrjp2c8ECBXwnvMKHs0wzvAGGecG0ovDSLE66UWmlh3mEi3w/dnp+Xh6w8AhXdE9P+KdpSAZyz9VCFnPgjecZM9fgzTsu7qDmuKKWIWpCqEKYsFnsGBzg1WH8gJ0L8GlwOiRXYSU9cvRFFnYbkmirPO/XkMKdDorwVpCIprSpoGLh8wpbSJSUa3l1A2s1WfIr6w+jZXWEQpWenWCpAIt0Pu/xfTpUlDaWjvoT8/c6/tqVeTautk/mTXyspjXJwoNVa2fN2q4pHyJ8diuvZUSPkp94JPMdpHF1b+z5X0bIbER9QNhE5HIG8hSdKPPVvoRpdq2+ftSymGKdQVUnHuy5mncz2fSUNC0eTPzIaJJv7MNp4IfxIGAsGzvzYB9dW/11sUuECID0XYRvTNEM/sRLDaMj5osJPx4qQTTvC9GVpdxy2fUUUo5bKW0nBCuZfCv7o7g7c4pxjSeW/GBxkh7oRS4qFo2t+ZAJkQc/MNqnlOHAV+MzK3Lzo00djOcURGFkfQDI7lkU39rDSrpk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
